apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: ap-south-1

nodeGroups:
  - name: core
    instanceType: t3.medium
    desiredCapacity: 1

  - name: application
    instanceType: t3.medium
    desiredCapacity: 1
    labels:
      role: app

  - name: nginx
    instanceType: t3.medium
    desiredCapacity: 1
    labels:
      role: nginx
